import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer/footer'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Landing from '@/components/landing/landing'
import Reduce from '@/components/reduce/reduce'
import Forest from '@/components/forestation/forest'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Landing></Landing>
        <Reduce></Reduce>
        <Forest></Forest>
      </main>
      <Footer></Footer>
    </>
  )
}
