import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer/footer'
import { Fredoka } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Landing from '@/components/landing/landing'
import Reduce from '@/components/reduce/reduce'
import Forest from '@/components/forestation/forest'
import Industry from '@/components/industry/industry.jsx'
import Ocean from '@/components/ocean/ocean'
import Carbon from '@/components/carbon/carbon'

const fredoka = Fredoka({subsets:['latin'],weight:'400'});

export default function Home() {
  return (
    <>
      <Head>  
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${fredoka.className}`}>
        {/* <div className={styles.test}>
          <div className={styles.block}></div>
          <div className={styles.block2}></div>
        </div> */}
        <Landing></Landing>
        <Reduce></Reduce>
        <Forest></Forest>
        <Industry></Industry>
        <Carbon></Carbon>
        <Ocean></Ocean>
      </main>
      <Footer></Footer>
    </>
  )
}
